### ISSUE TITLE
Should be able to initialize Client with concurrentRequestLimit option

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks-brightcove-provider#10]
The Brightcove client has a `concurrentRequestLimit` option which can be set when creating a new Client instance: https://github.com/oddnetworks/oddworks-brightcove-provider/blob/master/lib/client.js#L59

It is not currently possible to set that option when initializing the provider: https://github.com/oddnetworks/oddworks-brightcove-provider/blob/master/index.js#L41

The initialize() function should probably accept `options.concurrentRequestLimit` and pass it to the Client constructor when creating a new Client instance.

**Comment by blainsmith** [comment]
@aljachimiak Perhaps assisting Everett on doing small node stuff like this will ease him into node and also will help him understand our provider pattern.

We can back him up, but this might be a small enough surface area in node not to get too overwhelmed. This helped you get started too right? You started on providers?

**Comment by aljachimiak** [comment]
@everettfranco - See how far you get here and then we can loop up and see how awesome you crushed it, or what's left.

**Comment by everett1989** [comment]
@aljachimiak Hey when you get time, can you take a look at my PR? https://github.com/oddnetworks/oddworks-brightcove-provider/pull/11

**Comment by blainsmith** [comment]
Fixed and pushed to NPM.
